apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: demotestguestbook
  labels:
    app: guestbook
    tier: frontend
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  # type: LoadBalancer
  # type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    # nodePort: 30042
  selector:
    app: guestbook
    tier: frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myservicea
  namespace: demotestguestbook
spec:
  rules:
  - host: guestbook
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
  ingressClassName: nginx
