apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: demotestguestbook
  labels:
    app: guestbook
    tier: frontend
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: LoadBalancer
  # type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30042
  selector:
    app: guestbook
    tier: frontend
